jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Обычные шаги сборки Docker образа
      - name: Build Docker Image
        run: docker build -t winfast91/nestjs-boilerplate:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push winfast91/nestjs-boilerplate:${{ github.sha }}

      # Шаги деплоя в зависимости от ветки
      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@195.133.41.51 'docker pull winfast91/nestjs-boilerplate:${{ github.sha }} && docker stop backend_main || true && docker rm backend_main || true && docker run -d --name backend_main -p 5000:3000 winfast91/nestjs-boilerplate:${{ github.sha }}'

      - name: Deploy to Server Dev
        if: github.ref == 'refs/heads/dev'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@195.133.41.51 'docker pull winfast91/nestjs-boilerplate:${{ github.sha }} && docker stop backend_dev || true && docker rm backend_dev || true && docker run -d --name backend_dev -p 4000:3000 winfast91/nestjs-boilerplate:${{ github.sha }}'
